openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Laboratory management for Web-In-Cloud system
  version: "1.0.0"
  title: Laboratory API
  contact:
    email: xmagulam@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
  - name: labs
    description: Laboratory API
  - name: labAnalyses
    description: Laboratory analyses API
  - name: sampleEvidences
    description: Sample evidences API
paths:
  "/lab":
    post:
      tags:
        - labs
      summary: Saves new lab definition
      operationId: createLab
      description: Use this method to initialize new laboratory in the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Laboratory"
            examples:
              request-sample:
                $ref: "#/components/examples/LaboratoryExample"
        description: Laboratory details to store
        required: true
      responses:
        "200":
          description: >-
            Value of stored laboratory
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Laboratory"
              examples:
                request-sample:
                  $ref: "#/components/examples/LaboratoryExample"
        "400":
          description: Missing mandatory properties of input object.
        "409":
          description: Entry with the specified id already exists

  "/lab/{laboratoryId}":
    delete:
      tags:
        - labs
      summary: Deletes specific laboratory
      operationId: deleteLaboratory
      description: Use this method to delete the specific laboratory from the system.
      parameters:
        - in: path
          name: laboratoryId
          description: pass the id of the particular laboratory
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Item deleted
        "404":
          description: Laboratory with such ID does not exist

  "/lab/{laboratoryId}/lab-analysis":
    get: 
      tags:
        - labAnalyses
      summary: Get all laboratory analyses
      operationId: getLabAnalysis
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of laboratory analyses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LaboratoryAnalysis"
              examples:
                response:
                  $ref: "#/components/examples/LaboratoryAnalysisExample"
        "404":
          description: Laboratory not found
    post:
      tags:
        - labAnalyses
      summary: Create a new laboratory analysis
      operationId: createLabAnalysis
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Laboratory analysis created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaboratoryAnalysis"
              examples:
                updated-response:
                  $ref: "#/components/examples/LaboratoryAnalysisExample"
        "400":
          description: Invalid input
        "404":
          description: Laboratory not found
  
  "/lab/{laboratoryId}/lab-analysis/{analysisId}":
    get:
      tags:
        - labAnalyses
      summary: Get laboratory analysis by ID
      operationId: getLabAnalysisById
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: analysisId
          in: path
          description: Analysis ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A laboratory analysis
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaboratoryAnalysis"
              examples:
                response:
                  $ref: "#/components/examples/LaboratoryAnalysisExample"
        "404":
          description: Laboratory or analysis not found
    put:
      tags:
        - labAnalyses
      summary: Update laboratory analysis by ID
      operationId: updateLabAnalysis
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: analysisId
          in: path
          description: Analysis ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Laboratory analysis updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LaboratoryAnalysis"
              examples:
                response:
                  $ref: "#/components/examples/LaboratoryAnalysisExample"
        "400":
          description: Invalid input
        "404":
          description: Laboratory or analysis not found
    delete:
      tags:
        - labAnalyses
      summary: Delete laboratory analysis by ID
      operationId: deleteLabAnalysis
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: analysisId
          in: path
          description: Analysis ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Laboratory analysis deleted
        "404":
          description: Laboratory or analysis not found
  
  "/lab/{laboratoryId}/sample-evidence":
    get:
      tags:
        - sampleEvidences
      summary: Get all sample evidences
      operationId: getSampleEvidence
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of sample evidences
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SampleEvidence"
              examples:
                response:
                  $ref: "#/components/examples/SampleEvidenceExample"
        "404":
          description: Laboratory not found
    post:
      tags:
        - sampleEvidences
      summary: Create a new sample evidence
      operationId: createSampleEvidence
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
      responses:
        "201":
          description: Sample evidence created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SampleEvidence"
              examples:
                updated-response:
                  $ref: "#/components/examples/SampleEvidenceExample"
        "400":
          description: Invalid input
        "404":
          description: Laboratory not found

  "/lab/{laboratoryId}/sample-evidence/{evidenceId}":
    get:
      tags:
        - sampleEvidences
      summary: Get sample evidence by ID
      operationId: getSampleEvidenceById
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: evidenceId
          in: path
          description: Evidence ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A sample evidence
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SampleEvidence"
              examples:
                response:
                  $ref: "#/components/examples/SampleEvidenceExample"
        "404":
          description: Laboratory or evidence not found
    put:
      tags:
        - sampleEvidences
      summary: Update sample evidence by ID
      operationId: updateSampleEvidence
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: evidenceId
          in: path
          description: Evidence ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sample evidence updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SampleEvidence"
              examples:
                response:
                  $ref: "#/components/examples/SampleEvidenceExample"
        "400":
          description: Invalid input
        "404":
          description: Laboratory or evidence not found
    delete:
      tags:
        - sampleEvidences
      summary: Delete sample evidence by ID
      operationId: deleteSampleEvidence
      parameters:
        - name: laboratoryId
          in: path
          description: Laboratory ID
          required: true
          schema:
            type: string
        - name: evidenceId
          in: path
          description: Evidence ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Sample evidence deleted
        "404":
          description: Laboratory or evidence not found

components:
  schemas:
    LaboratoryAnalysis:
      type: object
      required: [id, name, analyses, results, status]
      properties:
        id:
          type: string
          example: x321ab3
          description: Unique id of the entry in this waiting list
        name:
          type: string
          example: Jožko Púčik
          description: Name of patient
        analyses:
          type: array
          items:
            type: string
          example: [CRP, sugar, cholesterol]
        results:
          type: string
          example: "Lorem Ipsum latin results"
        status: 
          type: string
          example: pending
          description: Status of the analysis
      example:
        $ref: "#/components/examples/LaboratoryAnalysisExample"
    SampleEvidence:
      type: object
      required: [id, name, volume, testType, result, status]
      properties:
        id:
          type: string
          example: x321ab3
          description: Unique id of the entry in this waiting list
        name:
          type: string
          example: Jožko Púčik
          description: Name of patient
        volume:
          type: number
          example: 150
          description: Volume of the sample
        testType:
          type: string
          example: blood
          description: Type of the test
        result:
          type: string
          example: positive
          description: Result of the test
        status:
          type: string
          example: pending
          description: Status of the test
      example:
        $ref: "#/components/examples/SampleEvidenceExample"
    Laboratory:
      type: object
      required: [ "id", "name", "roomNumber"]
      properties:
        id:
          type: string
          example: laboratory-biochemistry
          description: Unique identifier of the laboratory
        name:
          type: string
          example: Biochemistry laboratory
          description: Human readable display name of the laboratory
        roomNumber:
          type: string
          example: 356 - 3rd floor
        labAnalyses:
          type: array
          items:
            $ref: '#/components/schemas/LaboratoryAnalysis'
        sampleEvidences:
          type: array
          items:
            $ref: '#/components/schemas/SampleEvidence'
      example:
        $ref: "#/components/examples/LaboratoryExample"
  examples:
    LaboratoryAnalysisExample:
      value:
        id: x321ab3
        name: Jožko Púčik
        analyses: [CRP, sugar, cholesterol]
        results: "Lorem Ipsum latin results"
        status: pending
    SampleEvidenceExample:
      value:
        id: x321ab3
        name: Jožko Púčik
        volume: 150
        testType: blood
        result: positive
        status: pending
    LaboratoryExample:
      value:
        id: laboratory-biochemistry
        name: Biochemistry laboratory
        roomNumber: 356 - 3rd floor
        labAnalyses: []
        sampleEvidences: []